"""
Django settings for LibraryProject project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-d#2@1%novv!u!j8r-dfq2nh-q#yikc05$17e4%1h$fbepxwd&t'

# SECURITY WARNING: don't run with debug turned on in production!
# Task 2: Security Best Practices - Set DEBUG to False in production
DEBUG = False  # Set to True for development, False for production

ALLOWED_HOSTS = ['*']  # Configure appropriately for production


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'LibraryProject.relationship_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'LibraryProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'LibraryProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Task 0: Custom User Model Configuration
# Set AUTH_USER_MODEL to use our custom user model
AUTH_USER_MODEL = 'relationship_app.CustomUser'


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (user uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Authentication settings
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'list_books'
LOGOUT_REDIRECT_URL = 'login'


# ============================================================================
# Task 2 & 3: Security Best Practices and HTTPS Configuration
# ============================================================================

# Task 3: HTTPS and Secure Redirects
# SECURE_SSL_REDIRECT: Redirect all non-HTTPS requests to HTTPS
# Set to True in production when SSL/TLS is configured
SECURE_SSL_REDIRECT = True  # Set to False for development without HTTPS

# HSTS (HTTP Strict Transport Security) Settings
# SECURE_HSTS_SECONDS: Instruct browsers to only access the site via HTTPS
SECURE_HSTS_SECONDS = 31536000  # 1 year in seconds

# SECURE_HSTS_INCLUDE_SUBDOMAINS: Include all subdomains in HSTS policy
SECURE_HSTS_INCLUDE_SUBDOMAINS = True

# SECURE_HSTS_PRELOAD: Allow HSTS preloading
SECURE_HSTS_PRELOAD = True

# Task 3: Enforce Secure Cookies
# SESSION_COOKIE_SECURE: Ensure session cookies are only transmitted over HTTPS
SESSION_COOKIE_SECURE = True  # Set to False for development without HTTPS

# CSRF_COOKIE_SECURE: Ensure CSRF cookies are only transmitted over HTTPS
CSRF_COOKIE_SECURE = True  # Set to False for development without HTTPS

# Task 2 & 3: Secure Headers
# X_FRAME_OPTIONS: Prevent site from being framed (clickjacking protection)
X_FRAME_OPTIONS = 'DENY'

# SECURE_CONTENT_TYPE_NOSNIFF: Prevent browsers from MIME-sniffing
SECURE_CONTENT_TYPE_NOSNIFF = True

# SECURE_BROWSER_XSS_FILTER: Enable browser's XSS filtering
SECURE_BROWSER_XSS_FILTER = True

# Task 2: Additional Security Settings
# SECURE_PROXY_SSL_HEADER: For reverse proxy setups
# Uncomment and configure if behind a reverse proxy
# SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Content Security Policy (CSP) - Task 2
# Note: For full CSP implementation, consider using django-csp package
# For now, we'll set basic headers
# CSP can be implemented via middleware or response headers

# Additional security headers can be added via middleware
# For production, consider using django-cors-headers for CORS configuration

