"""
Django settings for LibraryProject project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-d#2@1%novv!u!j8r-dfq2nh-q#yikc05$17e4%1h$fbepxwd&t'

# SECURITY WARNING: don't run with debug turned on in production!
# Task 2: Security Best Practices - Set DEBUG to False in production
# IMPORTANT: Set DEBUG = True for development, DEBUG = False for production
DEBUG = True  # Change to False in production

# Task 2: Configure ALLOWED_HOSTS appropriately for production
# For development: ALLOWED_HOSTS = []
# For production: ALLOWED_HOSTS = ['yourdomain.com', 'www.yourdomain.com']
ALLOWED_HOSTS = []  # Configure appropriately for production


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'LibraryProject.bookshelf',
    'LibraryProject.relationship_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Task 2 Step 4: Content Security Policy (CSP) - Custom middleware for CSP headers
    'LibraryProject.bookshelf.middleware.CSPMiddleware',
]

ROOT_URLCONF = 'LibraryProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'LibraryProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Task 0 Step 2: Update Settings to Use the Custom User Model
# Configure Django to use this custom user model for all user-related functionalities
# Set the AUTH_USER_MODEL to point to your new custom user model
AUTH_USER_MODEL = 'bookshelf.CustomUser'


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (user uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Authentication settings
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'list_books'
LOGOUT_REDIRECT_URL = 'login'


# ============================================================================
# Task 2 & 3: Security Best Practices and HTTPS Configuration
# ============================================================================

# ============================================================================
# Task 3: HTTPS and Secure Redirects Configuration
# ============================================================================
# IMPORTANT: These settings should be True in production with HTTPS,
#            but False in development without HTTPS

# Task 3 Step 1: Configure Django for HTTPS Support
# SECURE_SSL_REDIRECT: Set to True to redirect all non-HTTPS requests to HTTPS
# This ensures all HTTP traffic is automatically redirected to HTTPS
SECURE_SSL_REDIRECT = False  # Set to True in production with HTTPS

# Task 3 Step 1: HSTS (HTTP Strict Transport Security) Settings
# SECURE_HSTS_SECONDS: Set an appropriate value (e.g., 31536000 for one year)
# This instructs browsers to only access the site via HTTPS for the specified time
SECURE_HSTS_SECONDS = 31536000  # 1 year in seconds (31536000)

# Task 3 Step 1: SECURE_HSTS_INCLUDE_SUBDOMAINS: Set to True
# This includes all subdomains in the HSTS policy
SECURE_HSTS_INCLUDE_SUBDOMAINS = True

# Task 3 Step 1: SECURE_HSTS_PRELOAD: Set to True
# This allows HSTS preloading for better security
SECURE_HSTS_PRELOAD = True

# Task 2 Step 1 & Task 3 Step 2: Enforce Secure Cookies
# SESSION_COOKIE_SECURE: Set to True to ensure session cookies are only transmitted over HTTPS
# This prevents session cookies from being sent over insecure HTTP connections
# Task 2 Step 1: Ensure CSRF_COOKIE_SECURE and SESSION_COOKIE_SECURE are set to True
SESSION_COOKIE_SECURE = True  # Set to False for development without HTTPS

# Task 2 Step 1 & Task 3 Step 2: CSRF_COOKIE_SECURE: Set to True
# This ensures CSRF cookies are only transmitted over HTTPS
# Prevents CSRF tokens from being intercepted over insecure connections
# Task 2 Step 1: Ensure CSRF_COOKIE_SECURE and SESSION_COOKIE_SECURE are set to True
CSRF_COOKIE_SECURE = True  # Set to False for development without HTTPS

# ============================================================================
# Task 2 & 3 Step 3: Implement Secure Headers
# ============================================================================

# Task 3 Step 3: X_FRAME_OPTIONS: Set to "DENY"
# This prevents your site from being framed and protects against clickjacking attacks
# Options: 'DENY' (no framing), 'SAMEORIGIN' (same origin only), 'ALLOWALL' (not recommended)
X_FRAME_OPTIONS = 'DENY'

# Task 2 Step 1 & Task 3 Step 3: SECURE_CONTENT_TYPE_NOSNIFF: Set to True
# This prevents browsers from MIME-sniffing a response away from the declared content-type
# Protects against MIME type confusion attacks
SECURE_CONTENT_TYPE_NOSNIFF = True

# Task 2 Step 1 & Task 3 Step 3: SECURE_BROWSER_XSS_FILTER: Set to True
# This enables the browser's XSS filtering and helps prevent cross-site scripting attacks
SECURE_BROWSER_XSS_FILTER = True

# Task 2: Additional Security Settings
# SECURE_PROXY_SSL_HEADER: For reverse proxy setups
# Uncomment and configure if behind a reverse proxy
# SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Content Security Policy (CSP) - Task 2
# Note: For full CSP implementation, consider using django-csp package
# For now, we'll set basic headers
# CSP can be implemented via middleware or response headers

# Additional security headers can be added via middleware
# For production, consider using django-cors-headers for CORS configuration

